// Copies the exact Lucide icons the product uses (its own lucide-react version) into
// assets/icons.js as { name: innerSVG }, merged with what is already there.
// Usage: node gen-icons.mjs <product-repo | lucide icons dir> icon-name …
// (Other icon sets: paste their inner SVG into assets/icons.js by hand, same shape.)
import fs from 'node:fs'
import path from 'node:path'

const [where, ...names] = process.argv.slice(2)
if (!where || !names.length) throw new Error('usage: node gen-icons.mjs <repo|icons-dir> icon-a icon-b …')
function iconsDir(p) {
  if (fs.existsSync(path.join(p, 'x.js')) && fs.existsSync(path.join(p, 'plus.js'))) return p
  const direct = path.join(p, 'node_modules/lucide-react/dist/esm/icons')
  if (fs.existsSync(direct)) return direct
  const pnpm = path.join(p, 'node_modules/.pnpm')
  if (fs.existsSync(pnpm)) {
    const hit = fs.readdirSync(pnpm).filter((d) => d.startsWith('lucide-react@')).sort().pop()
    if (hit) return path.join(pnpm, hit, 'node_modules/lucide-react/dist/esm/icons')
  }
  for (const sub of ['apps', 'packages']) {
    const d = path.join(p, sub)
    if (!fs.existsSync(d)) continue
    for (const app of fs.readdirSync(d)) {
      const r = path.join(d, app, 'node_modules/lucide-react/dist/esm/icons')
      if (fs.existsSync(r)) return r
    }
  }
  throw new Error(`no lucide-react icons under ${p}`)
}
const L = iconsDir(path.resolve(where))
const file = 'assets/icons.js'
const out = fs.existsSync(file) ? (await import(path.resolve(file))).ICONS : {}
for (const n of names) {
  let src = fs.readFileSync(`${L}/${n}.js`, 'utf8')
  while (!src.includes('const __iconNode')) {
    const m = src.match(/from '\.\/([^']+)'/)
    if (!m) throw new Error('no icon node for ' + n)
    src = fs.readFileSync(`${L}/${m[1]}`, 'utf8')
  }
  const node = eval(src.match(/const __iconNode = (\[[\s\S]*?\]);\n/)[1])
  out[n] = node.map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).filter(([k]) => k !== 'key').map(([k, v]) => `${k}="${v}"`).join(' ')}/>`).join('')
}
const ver = JSON.parse(fs.readFileSync(path.join(L, '../../../package.json'), 'utf8')).version
fs.writeFileSync(file, `// Lucide ${ver} (ISC) — generated by gen-icons.mjs\nexport const ICONS = ${JSON.stringify(out)}\n`)
console.log(Object.keys(out).length, 'icons in', file)
